### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by Dr-Horv** [fredagsdeploy/beer-o-clock#2]

**Comment by lindskogen** [comment]
Do we want to disable indexing of this site on google?

```
User-agent: *
Disallow: /
```

**Comment by Dr-Horv** [comment]
Rather the opposite, need better SEO!

**Comment by lindskogen** [comment]
Preview on Google result:

![image](https://user-images.githubusercontent.com/817046/108502518-3511bf00-72b3-11eb-8703-94bfc67b26a2.png)

**Comment by Dr-Horv** [comment]
🤩

**Comment by Dr-Horv** [comment]
@lindskogen PR?

**Comment by lindskogen** [comment]
That is the google result live right now. Check it for yourself! 😅

**Comment by Dr-Horv** [comment]
Done? @lindskogen

**Comment by lindskogen** [comment]
As far as I see it!
